# Generated by Django 2.2.4 on 2019-08-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VisitTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='姓名')),
                ('stu_id', models.CharField(max_length=10, verbose_name='学号')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('times', models.CharField(max_length=30, verbose_name='预约时间')),
                ('is_success', models.BooleanField(default=False, verbose_name='是否抢票成功')),
                ('ticket_id', models.CharField(max_length=15, verbose_name='票号')),
            ],
        ),
    ]
