# Generated by Django 2.2.4 on 2019-08-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitticket',
            name='ticket_id',
            field=models.CharField(max_length=15, null=True, verbose_name='票号'),
        ),
    ]
